# This is an example goreleaser.yaml file with some sane defaults. Make sure to
# check the documentation at http://goreleaser.com
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  algorithm: sha384
  name_template: SHA384SUMS

nfpms:
  - id: default
    maintainer: Jan Graichen <jan.graichen@hpi.de>
    description: Docker Volume Plugin for OpenStack Cinder
    license: MIT License
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./example/cinder.json
        dst: /etc/docker/cinder.json
        type: config
      - src: ./example/docker-plugin-cinder.socket
        dst: /etc/systemd/system/docker-plugin-cinder.socket
      - src: ./example/docker-plugin-cinder.service
        dst: /etc/systemd/system/docker-plugin-cinder.service

changelog:
  use: git

  groups:
    - title: Changes
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

  filters:
    exclude:
      - '^Merge pull request'

release:
  draft: False
