# This is an example goreleaser.yaml file with some sane defaults. Make sure to
# check the documentation at http://goreleaser.com

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  algorithm: sha384
  name_template: SHA384SUMS

changelog:
  use: git

  groups:
    - title: Changes
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

  filters:
    exclude:
      - '^Merge pull request'

release:
  draft: False
